"""Mash package public API.

This package provides source-loading templates and loaders used by GKC.
"""

from gkc.mash.core import (
    ClaimSummary,
    CommonsFileInfoResult,
    DataTemplate,
    URLFetchResult,
    WikibaseApiClient,
    WikibaseCacheRefreshResult,
    WikibaseEntitySchemaTemplate,
    WikibaseFullSyncResult,
    WikibaseItemTemplate,
    WikibaseLoader,
    WikibaseMashSourceAdapter,
    WikibasePropertyTemplate,
    WikibaseRecentChangesResult,
    WikipediaLoader,
    WikipediaMashSourceAdapter,
    WikipediaTemplate,
    apply_item_property_filters,
    apply_template_language_filter,
    discover_wikibase_entity_ids,
    extract_first_sparql_block,
    extract_sparql_blocks,
    fetch_commons_file_info,
    fetch_entity_rdf,
    fetch_entity_schema_json,
    fetch_entity_schema_specification,
    fetch_mediawiki_page_wikitext,
    fetch_property_labels,
    fetch_recent_entity_changes,
    fetch_url_resource,
    full_sync_wikibase_entity_cache,
    get_latest_cache_timestamp,
    refresh_entity_cache_from_recentchanges,
    strip_entity_identifiers,
)
from gkc.mash.protocols import MashSourceAdapter

__all__ = [
    "ClaimSummary",
    "CommonsFileInfoResult",
    "DataTemplate",
    "URLFetchResult",
    "WikibaseCacheRefreshResult",
    "WikibaseFullSyncResult",
    "MashSourceAdapter",
    "discover_wikibase_entity_ids",
    "full_sync_wikibase_entity_cache",
    "WikibaseMashSourceAdapter",
    "WikipediaMashSourceAdapter",
    "apply_item_property_filters",
    "apply_template_language_filter",
    "extract_first_sparql_block",
    "extract_sparql_blocks",
    "WikibaseApiClient",
    "WikibaseRecentChangesResult",
    "WikibaseLoader",
    "WikibaseItemTemplate",
    "WikibasePropertyTemplate",
    "WikibaseEntitySchemaTemplate",
    "WikipediaLoader",
    "WikipediaTemplate",
    "fetch_entity_rdf",
    "fetch_mediawiki_page_wikitext",
    "fetch_entity_schema_json",
    "fetch_entity_schema_specification",
    "fetch_commons_file_info",
    "fetch_url_resource",
    "fetch_property_labels",
    "fetch_recent_entity_changes",
    "get_latest_cache_timestamp",
    "refresh_entity_cache_from_recentchanges",
    "strip_entity_identifiers",
]
